### ISSUE TITLE
Cannot install due to errors

### ISSUE THREAD

**Issue by saro-saravanan** [WorldBrain/storex-backend-dexie#5]
npm install (or yarn) on my Windows development system yields the following errors. What am I missing? I followed the instructions in the storex repo. Thanks!

C:\Users\saro\app\storex-backend-dexie>npm install

> sinon@4.5.0 postinstall C:\Users\saro\app\storex-backend-dexie\node_modules\sinon
> node scripts/support-sinon.js

Have some ❤️ for Sinon? You can support the project via Open Collective:
 > https://opencollective.com/sinon/donate

> @worldbrain/storex-backend-dexie@0.1.0 prepare C:\Users\saro\app\storex-backend-dexie
> tsc

ts/index.ts:248:40 - error TS2694: Namespace '"C:/Users/saro/app/storex-backend-dexie/node_modules/@worldbrain/storex/lib/types/backend"' has no exported member 'OperationBatch'.

248     async executeBatch(batch : backend.OperationBatch) {
                                           ~~~~~~~~~~~~~~

ts/index.ts:259:25 - error TS2694: Namespace '"C:/Users/saro/app/storex-backend-dexie/node_modules/@worldbrain/storex/lib/types/backend"' has no exported member 'OperationBatch'.

259         batch : backend.OperationBatch,
                            ~~~~~~~~~~~~~~

ts/index.ts:398:28 - error TS2554: Expected 2 arguments, but got 3.

398         const dissection = dissectCreateObjectOperation(step, registry, {
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
399             generatePlaceholder: (() => {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
409             })()
    ~~~~~~~~~~~~~~~~
410         })
    ~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @worldbrain/storex-backend-dexie@0.1.0 prepare: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @worldbrain/storex-backend-dexie@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\saro\AppData\Roaming\npm-cache\_logs\2019-02-25T16_01_57_282Z-debug.log

**Comment by ShishKabab** [comment]
Argh, I've been having some chaos with different versions between all the different modules. I should implement everything with Git flow soon, so the master branch always works, with a separate development branch that can be broken. Right now in order to build the Dexie back-end manually, you'll need to also checkout and build Storex itself, and use `yarn link` (or `npm link`) to hook them together as described here:
https://github.com/WorldBrain/storex#building-for-development

**Comment by saro-saravanan** [comment]
Thanks. I did what has been suggested, please see evidence below, but I'm still getting the same results. In the storex directory, ran yarn link. In the storex-backend directory, ran yarn link @worldbrain/storex and then yarn:

C:\Users\saro\app\storex>yarn link
yarn link v1.13.0
warning package.json: No license field
warning package.json: No license field
success Registered "@worldbrain/storex".
info You can now run `yarn link "@worldbrain/storex"` in the projects where you want to use this package and it will be used instead.
Done in 0.10s.

C:\Users\saro\app\storex-backend-dexie>yarn link @worldbrain/storex
yarn link v1.13.0
warning package.json: No license field
success Using linked package for "@worldbrain/storex".
Done in 0.14s.

C:\Users\saro\app\storex-backend-dexie>yarn
yarn install v1.13.0
warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning @worldbrain/storex-backend-dexie@0.1.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ tsc
ts/index.ts:248:40 - error TS2694: Namespace '"C:/Users/saro/app/storex/lib/types/backend"' has no exported member 'OperationBatch'.

248     async executeBatch(batch : backend.OperationBatch) {
                                           ~~~~~~~~~~~~~~

ts/index.ts:259:25 - error TS2694: Namespace '"C:/Users/saro/app/storex/lib/types/backend"' has no exported member 'OperationBatch'.

259         batch : backend.OperationBatch,
                            ~~~~~~~~~~~~~~

ts/index.ts:398:28 - error TS2554: Expected 2 arguments, but got 3.

398         const dissection = dissectCreateObjectOperation(step, registry, {
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
399             generatePlaceholder: (() => {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
409             })()
    ~~~~~~~~~~~~~~~~
410         })
    ~~~~~~~~~~


Found 3 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by ShishKabab** [comment]
Ouch, today I'll look into testing everything together, publishing the lastest versions of everything and introducing Git flow for all the repos. Thanks for reporting this!

**Comment by ShishKabab** [comment]
All fixed and published on NPM! Let me know if it works on your end, and I'll close this issue  :)

**Comment by saro-saravanan** [comment]
Thanks, I’ll check it out tonight.

Sent from Mail for Windows 10

**Comment by saro-saravanan** [comment]
It worked - i.e., I don't get the error anymore, now I can actually try this out. Thanks!

**Comment by ShishKabab** [comment]
Very happy to hear that! Also created a reduced version of Git flow in every Storex repo, so everything in `master` should always work now.

**Comment by saro-saravanan** [comment]
Awesome, thanks!

**Comment by saro-saravanan** [comment]
A couple of more problems to report, not with the installation, but the running:

1. The single quotes in the following command in the package.json file are causing a problem running mocha in my environment. I was able to avoid the problem by deleting the single quotes:

"test:mocha:watch": "mocha -r source-map-support/register -r **'ts-node/register ts/**/*.test.ts'** --watch --watch-extensions ts"

2. Then when I run test:mocha:watch, I get a couple of errors:

C:\Users\saro\app\storex-backend-dexie>yarn test:mocha:watch
yarn run v1.13.0
warning package.json: No license field
$ mocha -r source-map-support/register -r ts-node/register ts/**/*.test.ts --watch --watch-extensions ts



  Dexie StorageBackend integration tests
    Individual operations
      √ should be able to create simple objects and find them again by string pk (448ms)
      √ should be able to create simple objects and find them again by string field
      √ should be able to create simple objects and find them again by boolean field
      √ should be able to find by $lt operator
      √ should be able to find by $lte operator
      √ should be able to find by $gt operator
      √ should be able to find by $gte operator
      √ should be able to order results in ascending order
      √ should be able to order results in descending order
      √ should be able to limit ascending results
      1) should be able to limit descending results
      √ should be able to update objects by string pk
      √ should be able to update objects by string field
      √ should correctly do batch operations containing only creates
      √ should support batch operations with complex createObject operations
      - should support batch operations with compound primary keys
      √ should be able to do complex creates
      √ should be able to delete single objects by pk
      √ should be able to delete multiple objects by pk
    Basics with auth example
      √ should do basic CRUD ops
      √ should handle connects relationships correctly

  Dexie StorageBackend full-text search with Memex stemmer tests
    √ should do full-text search of whole words

  Dexie StorageBackend batch operations
    √ should support batches with updateObject operations
    flattenBatch()
      √ should flatten batches with complex creates

  Dexie schema generation
    √ it should work


  23 passing (639ms)
  1 pending
  1 failing

  1) Dexie StorageBackend integration tests
       Individual operations
         should be able to limit descending results:
     Error: expect(received).toEqual(expected)

Expected value to equal:
  [ObjectContaining {"field": 3}, ObjectContaining {"field": 2}]
Received:
  [{"field": 3, "id": 3}, {"field": 1, "id": 2}]

Difference:

- Expected
+ Received

  Array [
-   ObjectContaining {
+   Object {
      "field": 3,
+     "id": 3,
    },
-   ObjectContaining {
-     "field": 2,
+   Object {
+     "field": 1,
+     "id": 2,
    },
  ]
      at C:\Users\saro\app\storex\ts\index.tests.ts:377:131
      at step (C:\Users\saro\app\storex\lib\index.tests.js:32:23)
      at Object.next (C:\Users\saro\app\storex\lib\index.tests.js:13:53)
      at fulfilled (C:\Users\saro\app\storex\lib\index.tests.js:4:58)

**Comment by ShishKabab** [comment]
Yes, I didn't have the time to fix that unit test yet, but should do so soon.

The `package.json` quite annoying. Removing them does work for single nested file (`ts/foo/bar.test.ts`), but not for top-level (`ts/index.ts`) and further nested files (`ts/spam/eggs/foo.test.ts`). Do you know of any cross-platform way to handle this? I thought Mocha itself handled the globbing if passed in verbatim?

**Comment by saro-saravanan** [comment]
After some quick Googling, I think using \” instead of single quote could work.  It works on Windows and if it also works for you on Linux, then that’s the solution.

Here’s the reference: https://stackoverflow.com/questions/48104380/single-quotes-not-working-in-package-json

Best,
Saro

Sent from Mail for Windows 10

**Comment by ShishKabab** [comment]
Works here! Change pushed to `develop` branches of both `storex` and `storex-backend-dexie`. Will push change to the rest of the Storex repos soon. Thanks for the help!

**Comment by ShishKabab** [comment]
Also, unit test is fixed on `develop`  :)

**Comment by saro-saravanan** [comment]
Great, thanks!
